package zerjioang.im.legalhack.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table SITIOS.
 */
public class Sitios {

    private Long id;
    /**
     * Not-null value.
     */
    private String IP;
    /**
     * Not-null value.
     */
    private String PORT;
    /**
     * Not-null value.
     */
    private String SERVERNAME;
    /**
     * Not-null value.
     */
    private String VISIBLENAME;
    private boolean LOGINENABLED;

    public Sitios() {
    }

    public Sitios(Long id) {
        this.id = id;
    }

    public Sitios(Long id, String IP, String PORT, String SERVERNAME, String VISIBLENAME, boolean LOGINENABLED) {
        this.id = id;
        this.IP = IP;
        this.PORT = PORT;
        this.SERVERNAME = SERVERNAME;
        this.VISIBLENAME = VISIBLENAME;
        this.LOGINENABLED = LOGINENABLED;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getIP() {
        return IP;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setIP(String IP) {
        this.IP = IP;
    }

    /**
     * Not-null value.
     */
    public String getPORT() {
        return PORT;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setPORT(String PORT) {
        this.PORT = PORT;
    }

    /**
     * Not-null value.
     */
    public String getSERVERNAME() {
        return SERVERNAME;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setSERVERNAME(String SERVERNAME) {
        this.SERVERNAME = SERVERNAME;
    }

    /**
     * Not-null value.
     */
    public String getVISIBLENAME() {
        return VISIBLENAME;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setVISIBLENAME(String VISIBLENAME) {
        this.VISIBLENAME = VISIBLENAME;
    }

    public boolean getLOGINENABLED() {
        return LOGINENABLED;
    }

    public void setLOGINENABLED(boolean LOGINENABLED) {
        this.LOGINENABLED = LOGINENABLED;
    }

}
